### ISSUE TITLE
TypeError on cancelReservation

### ISSUE THREAD

**Issue by danceroutine** [Spear99/CS408#2]
\>\>\>[POST]: /cancelReservation with data: {"reservationID":137}
/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/express/lib/response.js:1064:12)
    at ServerResponse.json (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/express/lib/response.js:243:14)
    at /u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/start.js:252:7
    at Query._callback (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/query.js:467:6)
    at Query.Sequence.end (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.OkPacket (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
    at Protocol._parsePacket (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Parser.js:75:12)

**Comment by danceroutine** [comment]
\>\>\>[POST]: /cancelReservation with data: {"reservationID":140}
/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: res.json is not a function
    at /u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/start.js:252:7
    at Query._callback (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/query.js:467:6)
    at Query.Sequence.end (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.OkPacket (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
    at Protocol._parsePacket (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/u/data/u99/pdelmora/CS408/CS408/src/main/webapp/cs408_app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)

**Comment by Bhuemann** [comment]
Fixed
